// Pre-generated hints for every word in the word bank.
// Each word maps to 3 closely associated clue words the imposter can use to blend in.

const HINTS = {

  // ── 🐾 Animals ──────────────────────────────────────────────────────────────────
  "elephant":    ["trunk", "big ears", "savanna"],
  "penguin":     ["tuxedo", "Antarctic", "waddle"],
  "dolphin":     ["echo", "flipper", "ocean"],
  "lion":        ["mane", "roar", "pride"],
  "tiger":       ["stripes", "jungle", "orange"],
  "panda":       ["bamboo", "China", "black-white"],
  "cheetah":     ["fast", "spots", "savanna"],
  "octopus":     ["tentacles", "ink", "eight"],
  "flamingo":    ["pink", "one-legged", "wading"],
  "gorilla":     ["silverback", "jungle", "strong"],
  "zebra":       ["stripes", "Africa", "herd"],
  "koala":       ["eucalyptus", "Australia", "tree"],
  "giraffe":     ["long neck", "Africa", "tall"],
  "crocodile":   ["teeth", "river", "cold-blooded"],
  "kangaroo":    ["pouch", "Australia", "jump"],
  "shark":       ["fin", "teeth", "ocean"],
  "parrot":      ["colorful", "talk", "tropical"],
  "eagle":       ["talons", "soar", "sharp eyes"],
  "wolf":        ["howl", "pack", "forest"],
  "bear":        ["hibernate", "fur", "claws"],
  "rabbit":      ["ears", "hop", "fluffy"],
  "monkey":      ["banana", "jungle", "climb"],
  "camel":       ["hump", "desert", "water"],
  "hippo":       ["river", "heavy", "big mouth"],
  "rhino":       ["horn", "Africa", "heavy"],
  "peacock":     ["feathers", "colorful tail", "blue"],
  "jellyfish":   ["sting", "transparent", "ocean"],
  "turtle":      ["shell", "slow", "sea"],
  "scorpion":    ["sting", "desert", "claws"],
  "bat":         ["night", "cave", "wings"],
  "deer":        ["antlers", "forest", "graceful"],
  "fox":         ["cunning", "orange", "bushy tail"],
  "owl":         ["night", "wisdom", "swivel head"],
  "seal":        ["flippers", "fish", "barking"],
  "whale":       ["ocean", "huge", "spout"],
  "horse":       ["gallop", "mane", "saddle"],
  "cow":         ["milk", "moo", "farm"],
  "chicken":     ["feathers", "egg", "cluck"],
  "duck":        ["quack", "pond", "beak"],
  "frog":        ["jump", "pond", "croak"],
  "snake":       ["slither", "venom", "scales"],
  "crab":        ["claws", "sideways", "beach"],
  "bee":         ["honey", "sting", "hive"],
  "butterfly":   ["wings", "colorful", "flower"],
  "lizard":      ["scales", "tongue", "reptile"],
  "hamster":     ["wheel", "cheeks", "small"],
  "squirrel":    ["acorn", "bushy tail", "tree"],
  "swan":        ["white", "graceful", "lake"],
  "pigeon":      ["city", "coo", "gray"],
  "salmon":      ["river", "pink", "swim upstream"],

  // ── 🍕 Food & Drinks ────────────────────────────────────────────────────────
  "pizza":       ["round", "cheese", "Italy"],
  "sushi":       ["rice", "raw fish", "Japan"],
  "burger":      ["bun", "beef", "fast food"],
  "noodles":     ["pasta", "slurp", "Asia"],
  "taco":        ["shell", "Mexico", "fold"],
  "chocolate":   ["sweet", "cocoa", "brown"],
  "ice cream":   ["cold", "scoop", "cone"],
  "sandwich":    ["bread", "filling", "lunch"],
  "salad":       ["greens", "healthy", "dressing"],
  "soup":        ["hot", "bowl", "liquid"],
  "bread":       ["bake", "loaf", "wheat"],
  "coffee":      ["caffeine", "hot", "morning"],
  "cake":        ["candles", "sweet", "birthday"],
  "rice":        ["grains", "Asia", "white"],
  "egg":         ["shell", "yolk", "breakfast"],
  "cheese":      ["yellow", "dairy", "France"],
  "bacon":       ["pork", "crispy", "breakfast"],
  "steak":       ["beef", "grill", "rare"],
  "shrimp":      ["pink", "seafood", "tail"],
  "dumpling":    ["dough", "filled", "steam"],
  "pancake":     ["flat", "syrup", "breakfast"],
  "waffle":      ["grid", "syrup", "crispy"],
  "donut":       ["ring", "fried", "glazed"],
  "cookie":      ["baked", "sweet", "round"],
  "popcorn":     ["cinema", "kernels", "salty"],
  "french fries":["potato", "crispy", "ketchup"],
  "hot dog":     ["sausage", "bun", "mustard"],
  "pasta":       ["Italy", "sauce", "noodle"],
  "burrito":     ["tortilla", "beans", "Mexico"],
  "ramen":       ["noodles", "broth", "Japan"],
  "milk":        ["white", "dairy", "cow"],
  "juice":       ["fruit", "sweet", "drink"],
  "beer":        ["foam", "hops", "cold"],
  "tea":         ["hot", "leaves", "cup"],
  "smoothie":    ["blended", "fruit", "cold"],
  "apple":       ["red", "fruit", "tree"],
  "banana":      ["yellow", "peel", "tropical"],
  "strawberry":  ["red", "seeds", "sweet"],
  "watermelon":  ["green", "red inside", "seeds"],
  "mango":       ["tropical", "yellow", "sweet"],
  "chicken":     ["wings", "grill", "white meat"],
  "tofu":        ["soy", "white", "bland"],
  "mushroom":    ["fungi", "umbrella", "earthy"],
  "avocado":     ["green", "guacamole", "healthy fat"],
  "croissant":   ["butter", "flaky", "France"],
  "kebab":       ["skewer", "grilled", "Middle East"],
  "curry":       ["spicy", "India", "sauce"],
  "soda":        ["fizzy", "sweet", "can"],
  "lemon":       ["yellow", "sour", "citrus"],

  // ── ⚽ Sports ────────────────────────────────────────────────────────────────
  "football":    ["goal", "kick", "stadium"],
  "basketball":  ["hoop", "dribble", "court"],
  "tennis":      ["racket", "net", "serve"],
  "swimming":    ["pool", "laps", "goggles"],
  "boxing":      ["gloves", "ring", "punch"],
  "golf":        ["club", "hole", "grass"],
  "volleyball":  ["net", "spike", "beach"],
  "baseball":    ["bat", "diamond", "America"],
  "cycling":     ["pedal", "wheel", "helmet"],
  "running":     ["sprint", "track", "shoes"],
  "skiing":      ["snow", "mountain", "poles"],
  "surfing":     ["waves", "board", "ocean"],
  "wrestling":   ["grapple", "mat", "pin"],
  "archery":     ["bow", "target", "arrow"],
  "rowing":      ["oar", "boat", "water"],
  "gymnastics":  ["flip", "mat", "balance"],
  "judo":        ["throw", "gi", "Japan"],
  "karate":      ["chop", "belt", "dojo"],
  "fencing":     ["sword", "mask", "lunge"],
  "diving":      ["pool", "platform", "splash"],
  "rugby":       ["oval ball", "tackle", "scrum"],
  "cricket":     ["bat", "wicket", "England"],
  "hockey":      ["stick", "puck", "ice"],
  "badminton":   ["shuttlecock", "racket", "net"],
  "table tennis":["paddle", "small ball", "fast"],
  "skateboarding":["board", "tricks", "halfpipe"],
  "snowboarding":["mountain", "tricks", "snow"],
  "climbing":    ["wall", "harness", "grip"],
  "bowling":     ["pins", "ball", "lane"],
  "darts":       ["bullseye", "throw", "board"],
  "weightlifting":["barbell", "heavy", "lift"],
  "shooting":    ["target", "gun", "aim"],
  "sailing":     ["wind", "boat", "sea"],
  "polo":        ["horse", "mallet", "field"],
  "curling":     ["broom", "stone", "ice"],
  "triathlon":   ["swim", "bike", "run"],
  "marathon":    ["long run", "42km", "endurance"],
  "relay":       ["baton", "team", "handoff"],
  "hurdles":     ["jump", "track", "barriers"],
  "javelin":     ["throw", "spear", "field"],
  "long jump":   ["sand pit", "runway", "leap"],
  "high jump":   ["bar", "leap", "back first"],
  "discus":      ["spinning", "throw", "circle"],
  "kayaking":    ["paddle", "river", "boat"],
  "BMX":         ["bike", "dirt", "tricks"],
  "water polo":  ["pool", "ball", "goal"],
  "handball":    ["goal", "court", "throw"],
  "lacrosse":    ["stick", "net", "Canada"],
  "squash":      ["racket", "small court", "rubber ball"],
  "parkour":     ["urban", "jumping", "obstacles"],

  // ── 🎬 Movies & TV ──────────────────────────────────────────────────────────
  "Titanic":     ["ship", "iceberg", "Rose"],
  "Avatar":      ["blue aliens", "Pandora", "3D"],
  "Frozen":      ["Elsa", "ice", "Let It Go"],
  "Lion King":   ["Simba", "Africa", "Hakuna Matata"],
  "Shrek":       ["ogre", "swamp", "Donkey"],
  "Inception":   ["dream", "spinning top", "layers"],
  "Matrix":      ["red pill", "Neo", "simulation"],
  "Joker":       ["clown", "Gotham", "laugh"],
  "Avengers":    ["superheroes", "Marvel", "Thanos"],
  "Batman":      ["cape", "Gotham", "dark"],
  "Spider-Man":  ["web", "New York", "Peter Parker"],
  "Harry Potter":["wizard", "Hogwarts", "magic"],
  "Star Wars":   ["lightsaber", "Darth Vader", "galaxy"],
  "Jurassic Park":["dinosaurs", "island", "DNA"],
  "Toy Story":   ["Woody", "Buzz", "toys come alive"],
  "Finding Nemo":["fish", "ocean", "clownfish"],
  "Interstellar":["space", "time", "wormhole"],
  "Gladiator":   ["Rome", "arena", "Russell Crowe"],
  "Parasite":    ["Korea", "rich family", "basement"],
  "Barbie":      ["pink", "Mattel", "Margot Robbie"],
  "Friends":     ["coffee", "New York", "six friends"],
  "Breaking Bad":["chemistry", "drugs", "desert"],
  "Game of Thrones":["dragons", "throne", "winter"],
  "Squid Game":  ["Korea", "red light green light", "survival"],
  "Stranger Things":["monster", "upside down", "80s"],
  "The Office":  ["workplace", "mockumentary", "Dwight"],
  "Oppenheimer": ["atomic bomb", "scientist", "Nolan"],
  "Dune":        ["desert", "sand worm", "spice"],
  "Moana":       ["ocean", "Hawaii", "Disney"],
  "Encanto":     ["Colombia", "magic house", "family"],
  "Coco":        ["Mexico", "Day of the Dead", "music"],
  "Up":          ["balloons", "house", "old man"],
  "WALL-E":      ["robot", "trash", "space"],
  "Inside Out":  ["emotions", "memory", "brain"],
  "Minions":     ["yellow", "bananas", "goggles"],
  "Fast and Furious":["cars", "racing", "family"],
  "Mission Impossible":["spy", "mask", "Tom Cruise"],
  "James Bond":  ["spy", "007", "shaken not stirred"],
  "The Notebook":["romance", "rain", "old couple"],
  "Twilight":    ["vampire", "love", "sparkle"],
  "Wednesday":   ["Addams Family", "dark", "school"],
  "Bridgerton":  ["London", "romance", "period drama"],
  "Peaky Blinders":["Birmingham", "cap", "gangster"],
  "Narcos":      ["Colombia", "drug lord", "Netflix"],
  "Sherlock":    ["detective", "London", "pipe"],
  "Black Mirror":["technology", "dark future", "twist"],
  "Euphoria":    ["high school", "drugs", "neon"],
  "Ted Lasso":   ["football coach", "kind", "biscuits"],
  "Succession":  ["rich family", "media empire", "Roy"],
  "Chernobyl":   ["nuclear", "explosion", "Russia"],

  // ── 💻 Technology ───────────────────────────────────────────────────────────
  "robot":       ["machine", "artificial", "program"],
  "internet":    ["web", "online", "connect"],
  "password":    ["secret", "login", "characters"],
  "keyboard":    ["type", "keys", "computer"],
  "screen":      ["display", "glass", "watch"],
  "camera":      ["photo", "lens", "capture"],
  "battery":     ["charge", "power", "drain"],
  "charger":     ["plug", "cable", "power"],
  "Wi-Fi":       ["wireless", "router", "signal"],
  "Bluetooth":   ["wireless", "pair", "short range"],
  "selfie":      ["photo", "front camera", "pose"],
  "emoji":       ["face", "symbol", "chat"],
  "email":       ["inbox", "send", "address"],
  "website":     ["URL", "browser", "page"],
  "app":         ["download", "phone", "icon"],
  "virus":       ["malware", "infect", "damage"],
  "hacker":      ["break in", "code", "steal"],
  "update":      ["new version", "install", "bug fix"],
  "download":    ["save", "file", "internet"],
  "upload":      ["send", "share", "cloud"],
  "cloud":       ["storage", "online", "sync"],
  "drone":       ["fly", "camera", "remote"],
  "satellite":   ["orbit", "signal", "space"],
  "GPS":         ["location", "map", "navigate"],
  "touchscreen": ["tap", "swipe", "glass"],
  "smartwatch":  ["wrist", "notifications", "fitness"],
  "headphones":  ["music", "ears", "wireless"],
  "speaker":     ["sound", "volume", "wireless"],
  "printer":     ["paper", "ink", "document"],
  "scanner":     ["copy", "document", "glass"],
  "laptop":      ["portable", "screen", "keyboard"],
  "tablet":      ["touch", "flat", "portable"],
  "server":      ["data", "host", "network"],
  "backup":      ["copy", "safe", "restore"],
  "pixel":       ["dot", "screen", "resolution"],
  "algorithm":   ["steps", "logic", "code"],
  "AI":          ["machine", "smart", "learn"],
  "coding":      ["program", "language", "computer"],
  "database":    ["store", "table", "query"],
  "firewall":    ["protect", "block", "security"],
  "social media":["post", "follow", "likes"],
  "streaming":   ["watch", "online", "live"],
  "podcast":     ["audio", "episode", "subscribe"],
  "notification":["alert", "buzz", "message"],
  "username":    ["handle", "account", "name"],
  "login":       ["access", "password", "account"],
  "chip":        ["small", "computer", "silicon"],
  "processor":   ["CPU", "speed", "compute"],
  "memory":      ["RAM", "storage", "data"],
  "software":    ["program", "install", "digital"],

  // ── 🌿 Nature ────────────────────────────────────────────────────────────────
  "volcano":     ["lava", "eruption", "hot"],
  "ocean":       ["salt water", "waves", "deep"],
  "forest":      ["trees", "green", "wildlife"],
  "desert":      ["sand", "hot", "dry"],
  "river":       ["flowing", "water", "current"],
  "mountain":    ["tall", "snow", "climb"],
  "waterfall":   ["cascade", "mist", "rocks"],
  "rainbow":     ["colors", "rain", "arc"],
  "thunder":     ["loud", "storm", "boom"],
  "lightning":   ["flash", "storm", "bolt"],
  "earthquake":  ["shake", "ground", "fault"],
  "tornado":     ["spin", "wind", "funnel"],
  "hurricane":   ["storm", "wind", "ocean"],
  "tsunami":     ["wave", "ocean", "earthquake"],
  "avalanche":   ["snow", "mountain", "slide"],
  "glacier":     ["ice", "slow", "mountain"],
  "cave":        ["dark", "underground", "stone"],
  "island":      ["surrounded by water", "tropical", "isolated"],
  "cliff":       ["drop", "rock", "edge"],
  "beach":       ["sand", "waves", "sun"],
  "lake":        ["still water", "freshwater", "swim"],
  "swamp":       ["muddy", "wet", "murky"],
  "jungle":      ["dense", "hot", "tropical"],
  "savanna":     ["grassland", "Africa", "dry"],
  "tundra":      ["frozen", "Arctic", "flat"],
  "sunrise":     ["morning", "orange", "dawn"],
  "sunset":      ["evening", "orange", "horizon"],
  "moon":        ["night", "glow", "orbit"],
  "stars":       ["night", "twinkle", "space"],
  "clouds":      ["sky", "white", "rain"],
  "snow":        ["white", "cold", "winter"],
  "rain":        ["wet", "drops", "cloud"],
  "fog":         ["misty", "grey", "low visibility"],
  "wind":        ["blow", "invisible", "air"],
  "flood":       ["water", "overflow", "disaster"],
  "coral reef":  ["underwater", "colorful", "fish"],
  "canyon":      ["deep", "rock", "Colorado"],
  "valley":      ["low", "between mountains", "green"],
  "plateau":     ["flat", "high", "table"],
  "lagoon":      ["shallow", "calm", "tropical"],
  "geyser":      ["hot water", "erupt", "steam"],
  "aurora":      ["lights", "Arctic", "colors"],
  "tide":        ["ocean", "moon", "rise fall"],
  "dune":        ["sand", "desert", "wave"],
  "mangrove":    ["coastal", "roots in water", "tropical"],
  "wildfire":    ["burn", "forest", "smoke"],
  "drought":     ["no rain", "dry", "crop failure"],
  "seasons":     ["four", "change", "weather"],
  "soil":        ["dirt", "ground", "grow"],
  "fossil":      ["ancient", "bone", "rock"],

  // ── 💼 Occupations ───────────────────────────────────────────────────────────
  "doctor":      ["hospital", "medicine", "health"],
  "teacher":     ["school", "lesson", "students"],
  "pilot":       ["cockpit", "fly", "airport"],
  "chef":        ["cook", "kitchen", "restaurant"],
  "firefighter": ["fire", "hose", "rescue"],
  "police officer":["badge", "law", "patrol"],
  "nurse":       ["hospital", "care", "injection"],
  "lawyer":      ["court", "defend", "law"],
  "engineer":    ["build", "design", "technical"],
  "artist":      ["paint", "create", "canvas"],
  "dentist":     ["teeth", "drill", "mouth"],
  "farmer":      ["crops", "land", "harvest"],
  "soldier":     ["uniform", "war", "army"],
  "scientist":   ["lab", "experiment", "research"],
  "actor":       ["film", "stage", "perform"],
  "singer":      ["voice", "microphone", "stage"],
  "driver":      ["wheel", "road", "vehicle"],
  "builder":     ["construction", "bricks", "tools"],
  "sailor":      ["ship", "sea", "navy"],
  "astronaut":   ["space", "rocket", "orbit"],
  "photographer":["camera", "photo", "shoot"],
  "journalist":  ["news", "write", "report"],
  "judge":       ["court", "gavel", "verdict"],
  "banker":      ["money", "finance", "vault"],
  "designer":    ["create", "visual", "style"],
  "plumber":     ["pipes", "water", "fix"],
  "electrician": ["wires", "power", "circuit"],
  "mechanic":    ["car", "engine", "repair"],
  "carpenter":   ["wood", "build", "tools"],
  "barber":      ["hair", "scissors", "cut"],
  "librarian":   ["books", "quiet", "shelves"],
  "security guard":["protect", "uniform", "watch"],
  "postman":     ["letters", "deliver", "bags"],
  "waiter":      ["restaurant", "serve", "menu"],
  "cashier":     ["till", "money", "checkout"],
  "pharmacist":  ["medicine", "pills", "prescription"],
  "surgeon":     ["operate", "hospital", "scalpel"],
  "coach":       ["train", "team", "sport"],
  "referee":     ["whistle", "rules", "fair"],
  "lifeguard":   ["pool", "rescue", "swim"],
  "architect":   ["design", "building", "blueprint"],
  "programmer":  ["code", "computer", "software"],
  "accountant":  ["numbers", "tax", "money"],
  "psychologist":["mind", "therapy", "mental health"],
  "vet":         ["animals", "clinic", "treat"],
  "translator":  ["language", "interpret", "words"],
  "detective":   ["clues", "mystery", "solve"],
  "musician":    ["instrument", "music", "perform"],
  "painter":     ["brush", "canvas", "color"],
  "dancer":      ["move", "rhythm", "stage"],

  // ── ✈️ Travel ────────────────────────────────────────────────────────────────
  "airport":     ["plane", "departure", "terminal"],
  "passport":    ["travel", "document", "border"],
  "hotel":       ["room", "stay", "bed"],
  "luggage":     ["bag", "pack", "wheels"],
  "ticket":      ["fly", "entry", "book"],
  "beach":       ["sand", "sea", "sun"],
  "museum":      ["art", "history", "exhibit"],
  "map":         ["navigate", "route", "paper"],
  "tour guide":  ["show around", "local", "group"],
  "souvenir":    ["gift", "memory", "shop"],
  "visa":        ["permit", "travel", "stamp"],
  "customs":     ["border", "check", "declare"],
  "boarding":    ["gate", "plane", "pass"],
  "taxi":        ["car", "hire", "city"],
  "train":       ["rail", "station", "track"],
  "cruise":      ["ship", "ocean", "holiday"],
  "camping":     ["tent", "outdoor", "fire"],
  "backpack":    ["carry", "travel", "hike"],
  "hostel":      ["cheap", "bunk bed", "travelers"],
  "resort":      ["luxury", "pool", "all inclusive"],
  "landmark":    ["famous", "tourist", "photo"],
  "monument":    ["stone", "history", "tall"],
  "ruins":       ["ancient", "broken", "history"],
  "cathedral":   ["church", "tall", "gothic"],
  "market":      ["buy", "sell", "stalls"],
  "ferry":       ["boat", "cross", "water"],
  "bus":         ["route", "stop", "public"],
  "highway":     ["road", "fast", "long"],
  "border":      ["cross", "passport", "country"],
  "check-in":    ["hotel", "desk", "room key"],
  "jet lag":     ["tired", "time zone", "travel"],
  "layover":     ["wait", "airport", "connecting"],
  "safari":      ["wildlife", "Africa", "jeep"],
  "road trip":   ["car", "long drive", "adventure"],
  "hot air balloon":["sky", "float", "basket"],
  "waterpark":   ["slides", "water", "fun"],
  "theme park":  ["rides", "Disney", "fun"],
  "zoo":         ["animals", "cage", "family"],
  "aquarium":    ["fish", "tank", "underwater"],
  "sunscreen":   ["protect", "sun", "cream"],
  "mosquito":    ["bite", "buzz", "tropical"],
  "time zone":   ["hours", "clock", "travel"],
  "local food":  ["culture", "eat", "taste"],
  "exchange rate":["money", "convert", "bank"],
  "travel insurance":["protect", "medical", "trip"],

  // ── 🎵 Music ────────────────────────────────────────────────────────────────
  "guitar":      ["strings", "rock", "strum"],
  "piano":       ["keys", "classical", "black white"],
  "drums":       ["beat", "sticks", "loud"],
  "violin":      ["bow", "strings", "classical"],
  "microphone":  ["sing", "amplify", "stage"],
  "concert":     ["live", "crowd", "tickets"],
  "song":        ["lyrics", "melody", "sing"],
  "melody":      ["tune", "notes", "hum"],
  "beat":        ["rhythm", "drum", "pulse"],
  "lyrics":      ["words", "sing", "rhyme"],
  "album":       ["songs", "release", "tracklist"],
  "band":        ["group", "musicians", "play together"],
  "singer":      ["voice", "stage", "microphone"],
  "DJ":          ["mix", "turntable", "club"],
  "bass":        ["low", "guitar", "deep"],
  "trumpet":     ["brass", "blow", "jazz"],
  "flute":       ["blow", "silver", "classical"],
  "harp":        ["strings", "pluck", "angel"],
  "saxophone":   ["jazz", "wind", "curved"],
  "keyboard":    ["keys", "electronic", "piano"],
  "chorus":      ["repeat", "loud", "main part"],
  "verse":       ["story", "section", "before chorus"],
  "bridge":      ["transition", "middle", "different"],
  "remix":       ["new version", "DJ", "different beat"],
  "cover":       ["another artist", "same song", "version"],
  "live show":   ["concert", "stage", "audience"],
  "festival":    ["outdoor", "many artists", "camping"],
  "tour":        ["travel", "concerts", "cities"],
  "record":      ["studio", "release", "vinyl"],
  "playlist":    ["songs", "queue", "Spotify"],
  "earphones":   ["ears", "listen", "wire"],
  "speaker":     ["sound", "Bluetooth", "volume"],
  "vinyl":       ["record", "old", "spin"],
  "radio":       ["broadcast", "frequency", "antenna"],
  "rap":         ["rhyme", "fast", "hip-hop"],
  "jazz":        ["saxophone", "improvise", "America"],
  "rock":        ["guitar", "loud", "band"],
  "pop":         ["popular", "catchy", "charts"],
  "classical":   ["orchestra", "old", "serious"],
  "tempo":       ["speed", "fast slow", "beat"],
  "rhythm":      ["pattern", "beat", "timing"],
  "harmony":     ["together", "blend", "voices"],
  "solo":        ["alone", "one person", "spotlight"],
  "duet":        ["two people", "together", "sing"],
  "music video": ["YouTube", "visual", "song"],
  "streaming":   ["Spotify", "online", "digital"],
  "autotune":    ["pitch", "electronic", "voice"],
  "Grammy":      ["award", "music", "trophy"],
  "fan":         ["love", "follow", "crowd"],
  "rehearsal":   ["practice", "prepare", "before show"],

  // ── 🎮 Video Games ──────────────────────────────────────────────────────────
  "Mario":       ["Nintendo", "mushroom", "jump"],
  "Minecraft":   ["blocks", "build", "sandbox"],
  "Fortnite":    ["battle royale", "build", "skins"],
  "Roblox":      ["kids", "user-made", "avatar"],
  "Pokemon":     ["catch", "evolve", "Pikachu"],
  "Zelda":       ["Link", "Nintendo", "adventure"],
  "FIFA":        ["football", "EA", "teams"],
  "Call of Duty":["shooter", "war", "multiplayer"],
  "Among Us":    ["imposter", "spaceship", "vote"],
  "GTA":         ["city", "crime", "cars"],
  "controller":  ["buttons", "joystick", "console"],
  "joystick":    ["control", "fly", "arcade"],
  "level":       ["stage", "progress", "unlock"],
  "boss":        ["hard enemy", "final", "fight"],
  "health bar":  ["HP", "damage", "red bar"],
  "respawn":     ["come back", "die", "restart"],
  "game over":   ["fail", "lose", "screen"],
  "cheat code":  ["hack", "unlock", "shortcut"],
  "save point":  ["checkpoint", "progress", "rescue"],
  "loot":        ["items", "collect", "chest"],
  "inventory":   ["items", "bag", "carry"],
  "multiplayer": ["online", "friends", "compete"],
  "sandbox":     ["free play", "build", "explore"],
  "open world":  ["explore", "freedom", "big map"],
  "dungeon":     ["dark", "monsters", "underground"],
  "quest":       ["mission", "objective", "reward"],
  "mission":     ["task", "complete", "goal"],
  "cutscene":    ["video", "story", "cinematic"],
  "tutorial":    ["learn", "beginner", "guide"],
  "leaderboard": ["ranking", "top players", "score"],
  "achievement": ["unlock", "badge", "complete"],
  "skin":        ["costume", "appearance", "buy"],
  "DLC":         ["extra content", "buy", "add-on"],
  "patch":       ["update", "fix", "new version"],
  "speedrun":    ["fast", "record", "skip"],
  "glitch":      ["bug", "broken", "exploit"],
  "sniper":      ["long range", "scope", "one shot"],
  "reload":      ["ammo", "gun", "pause"],
  "crafting":    ["build", "resources", "combine"],
  "farming":     ["resources", "grind", "collect"],
  "PvP":         ["player vs player", "compete", "fight"],
  "esports":     ["professional", "compete", "tournament"],
  "streaming":   ["Twitch", "watch", "live"],
  "console":     ["PlayStation", "Xbox", "play"],
  "PC gaming":   ["mouse", "keyboard", "computer"],
  "mobile game": ["phone", "tap", "casual"],
  "arcade":      ["coin", "classic", "cabinet"],
  "retro":       ["old", "classic", "pixel"],
  "co-op":       ["team", "together", "friends"],
  "character":   ["avatar", "hero", "choose"],

  // ── 🧪 Science ──────────────────────────────────────────────────────────────
  "gravity":     ["fall", "weight", "Earth"],
  "atom":        ["tiny", "element", "nucleus"],
  "DNA":         ["genes", "double helix", "life"],
  "cell":        ["microscopic", "life", "biology"],
  "virus":       ["infect", "spread", "sick"],
  "evolution":   ["Darwin", "change", "adapt"],
  "black hole":  ["space", "suck in", "gravity"],
  "solar system":["planets", "sun", "orbit"],
  "photosynthesis":["plants", "sunlight", "oxygen"],
  "volcano":     ["lava", "erupt", "hot"],
  "magnet":      ["attract", "poles", "metal"],
  "electricity": ["power", "current", "wire"],
  "radiation":   ["energy", "waves", "dangerous"],
  "chemical":    ["substance", "react", "lab"],
  "reaction":    ["change", "mix", "result"],
  "experiment":  ["test", "lab", "hypothesis"],
  "microscope":  ["zoom", "tiny", "lens"],
  "telescope":   ["stars", "far away", "lens"],
  "rocket":      ["launch", "space", "fire"],
  "orbit":       ["circle", "planet", "satellite"],
  "planet":      ["round", "space", "orbit"],
  "galaxy":      ["stars", "spiral", "Milky Way"],
  "asteroid":    ["rock", "space", "orbit"],
  "comet":       ["ice", "tail", "streak"],
  "star":        ["bright", "night sky", "hot"],
  "blood":       ["red", "veins", "oxygen"],
  "brain":       ["think", "neurons", "head"],
  "heart":       ["beat", "pump", "love"],
  "bone":        ["skeleton", "hard", "calcium"],
  "muscle":      ["flex", "move", "strong"],
  "oxygen":      ["breathe", "air", "gas"],
  "carbon dioxide":["breathe out", "gas", "greenhouse"],
  "hydrogen":    ["lightest", "gas", "water"],
  "water":       ["liquid", "clear", "H2O"],
  "acid":        ["sour", "corrode", "pH"],
  "crystal":     ["clear", "structure", "mineral"],
  "laser":       ["beam", "light", "precise"],
  "X-ray":       ["bone", "medical", "radiation"],
  "vaccine":     ["protect", "immune", "injection"],
  "clone":       ["copy", "identical", "DNA"],
  "mutation":    ["change", "DNA", "evolution"],
  "fossil":      ["ancient", "bone", "rock"],
  "extinction":  ["gone", "dinosaur", "forever"],
  "ecosystem":   ["nature", "balance", "animals plants"],
  "ocean floor": ["deep", "pressure", "dark"],
  "lightning":   ["flash", "storm", "electricity"],
  "tornado":     ["spin", "wind", "funnel"],
  "earthquake":  ["shake", "fault", "Richter"],
  "tsunami":     ["giant wave", "earthquake", "ocean"],
  "nitrogen":    ["gas", "air", "plants"],

  // ── 🏛️ History ───────────────────────────────────────────────────────────────
  "pyramid":     ["Egypt", "ancient", "pharaoh"],
  "gladiator":   ["Rome", "arena", "fight"],
  "pirate":      ["ship", "treasure", "skull"],
  "knight":      ["armor", "sword", "castle"],
  "samurai":     ["Japan", "sword", "honor"],
  "Viking":      ["Norse", "ship", "raid"],
  "pharaoh":     ["Egypt", "ruler", "pyramid"],
  "emperor":     ["ruler", "empire", "power"],
  "revolution":  ["overthrow", "change", "people"],
  "war":         ["fight", "soldiers", "conflict"],
  "castle":      ["stone", "knights", "tower"],
  "throne":      ["king", "seat", "power"],
  "crown":       ["king", "gold", "head"],
  "sword":       ["blade", "fight", "steel"],
  "cannon":      ["iron", "gunpowder", "boom"],
  "Columbus":    ["America", "1492", "explorer"],
  "Napoleon":    ["France", "short", "general"],
  "Cleopatra":   ["Egypt", "queen", "ancient"],
  "Caesar":      ["Rome", "Julius", "betrayal"],
  "Gandhi":      ["India", "peace", "independence"],
  "World War":   ["global", "soldiers", "1914 or 1939"],
  "Cold War":    ["USA USSR", "spy", "nuclear"],
  "moon landing":["1969", "Apollo", "Neil Armstrong"],
  "slavery":     ["forced", "chains", "abolished"],
  "democracy":   ["vote", "people", "election"],
  "plague":      ["death", "disease", "rats"],
  "famine":      ["hunger", "crops", "death"],
  "empire":      ["big", "ruler", "conquer"],
  "colony":      ["settled", "foreign", "control"],
  "treaty":      ["peace", "agreement", "sign"],
  "election":    ["vote", "candidate", "win"],
  "protest":     ["march", "signs", "change"],
  "independence":["free", "nation", "declare"],
  "invasion":    ["attack", "army", "enter"],
  "ancient Rome":["colosseum", "Julius Caesar", "Latin"],
  "ancient Egypt":["pyramids", "pharaoh", "hieroglyphs"],
  "Middle Ages": ["knights", "castles", "1000 AD"],
  "Renaissance": ["art", "science", "Florence"],
  "Industrial Revolution":["factories", "steam engine", "1800s"],
  "Olympic Games":["Greece", "sports", "gold medal"],
  "Silk Road":   ["trade", "China", "Asia"],
  "printing press":["books", "Gutenberg", "mass print"],
  "gunpowder":   ["explosion", "China", "weapon"],
  "compass":     ["direction", "navigate", "north"],
  "Titanic":     ["ship", "iceberg", "1912"],
  "Berlin Wall": ["Germany", "divide", "fall 1989"],
  "apartheid":   ["South Africa", "racism", "segregation"],
  "Holocaust":   ["Nazi", "Jews", "genocide"],
  "atomic bomb": ["nuclear", "Japan", "1945"],
  "space race":  ["USA USSR", "moon", "1960s"],

  // ── 🧁 Desserts ──────────────────────────────────────────────────────────────
  "chocolate cake":["layers", "birthday", "frosting"],
  "ice cream":   ["cold", "scoop", "sweet"],
  "donut":       ["ring", "glazed", "fried"],
  "brownie":     ["chocolate", "square", "fudgy"],
  "cookie":      ["baked", "sweet", "round"],
  "cupcake":     ["small cake", "frosting", "party"],
  "cheesecake":  ["cream cheese", "base", "New York"],
  "pudding":     ["soft", "creamy", "warm"],
  "pie":         ["crust", "filling", "bake"],
  "waffle":      ["grid", "syrup", "crispy"],
  "pancake":     ["flat", "syrup", "stack"],
  "crepe":       ["thin", "France", "fold"],
  "macaron":     ["colorful", "sandwich cookie", "France"],
  "eclair":      ["choux pastry", "oblong", "chocolate"],
  "muffin":      ["cup", "blueberry", "bake"],
  "lollipop":    ["stick", "round", "suck"],
  "gummy bear":  ["chewy", "colorful", "bears"],
  "marshmallow": ["soft", "white", "fire"],
  "cotton candy":["pink", "spun sugar", "carnival"],
  "candy bar":   ["chocolate", "caramel", "wrapper"],
  "tart":        ["pastry", "filling", "open top"],
  "cinnamon roll":["spiral", "frosting", "warm"],
  "banana bread":["moist", "loaf", "banana"],
  "shortcake":   ["crumbly", "strawberry", "cream"],
  "tiramisu":    ["coffee", "mascarpone", "Italy"],
  "mousse":      ["airy", "chocolate", "cold"],
  "sorbet":      ["frozen", "fruit", "no dairy"],
  "gelato":      ["Italian", "dense", "creamy"],
  "popsicle":    ["stick", "frozen", "fruity"],
  "flan":        ["caramel", "custard", "wobble"],
  "churro":      ["fried dough", "cinnamon", "Spain"],
  "baklava":     ["honey", "nuts", "phyllo"],
  "mochi":       ["rice cake", "Japan", "chewy"],
  "profiterole": ["choux pastry", "cream", "chocolate"],
  "Swiss roll":  ["spiral", "cream", "sponge"],
  "red velvet":  ["red", "cream cheese frosting", "layered"],
  "carrot cake": ["orange", "cream cheese", "moist"],
  "lemon tart":  ["sour", "pastry", "yellow"],
  "milkshake":   ["blended", "thick", "straw"],
  "caramel":     ["sticky", "golden", "sweet"],
  "toffee":      ["hard", "chewy", "buttery"],
  "fudge":       ["dense", "chocolate", "square"],
  "meringue":    ["egg white", "white", "crispy"],
  "custard":     ["yellow", "creamy", "warm"],
  "whipped cream":["light", "white", "spray"],
  "jam":         ["spread", "fruit", "jar"],
  "honey":       ["bee", "golden", "sweet"],
  "hot chocolate":["warm", "cocoa", "winter"],
  "fruit salad": ["mixed", "healthy", "colorful"],
  "croissant":   ["buttery", "flaky", "France"],

  // ── 🌃 Cities ────────────────────────────────────────────────────────────────
  "Tokyo":       ["Japan", "busy", "technology"],
  "Paris":       ["Eiffel Tower", "France", "romance"],
  "New York":    ["skyscrapers", "USA", "Times Square"],
  "London":      ["Big Ben", "UK", "red bus"],
  "Dubai":       ["tall buildings", "desert", "luxury"],
  "Rome":        ["Colosseum", "Italy", "ancient"],
  "Sydney":      ["Opera House", "Australia", "harbour"],
  "Barcelona":   ["Gaudi", "Spain", "beach"],
  "Istanbul":    ["Bosphorus", "Turkey", "mosques"],
  "Bangkok":     ["temples", "Thailand", "street food"],
  "Singapore":   ["clean", "Asia", "small island"],
  "Cairo":       ["pyramids", "Egypt", "Nile"],
  "Mumbai":      ["Bollywood", "India", "busy"],
  "Los Angeles": ["Hollywood", "USA", "sunshine"],
  "Toronto":     ["CN Tower", "Canada", "multicultural"],
  "Berlin":      ["history", "Germany", "wall"],
  "Amsterdam":   ["canals", "Netherlands", "bikes"],
  "Seoul":       ["K-pop", "South Korea", "modern"],
  "Mexico City": ["Mexico", "ancient", "big"],
  "Buenos Aires":["Argentina", "tango", "steak"],
  "Nairobi":     ["Kenya", "safari", "Africa"],
  "Lagos":       ["Nigeria", "biggest Africa", "busy"],
  "Cape Town":   ["Table Mountain", "South Africa", "coast"],
  "Casablanca":  ["Morocco", "port", "film"],
  "Marrakech":   ["Morocco", "market", "colorful"],
  "Athens":      ["Parthenon", "Greece", "ancient"],
  "Prague":      ["castle", "Czechia", "old town"],
  "Vienna":      ["Mozart", "Austria", "classical"],
  "Budapest":    ["baths", "Hungary", "Danube"],
  "Lisbon":      ["trams", "Portugal", "hilly"],
  "Moscow":      ["Kremlin", "Russia", "cold"],
  "Beijing":     ["Great Wall", "China", "capital"],
  "Shanghai":    ["China", "modern", "Bund"],
  "Hong Kong":   ["skyscrapers", "China", "island"],
  "Taipei":      ["Taiwan", "night market", "101"],
  "Jakarta":     ["Indonesia", "traffic", "tropical"],
  "Manila":      ["Philippines", "busy", "tropical"],
  "Kuala Lumpur":["Petronas towers", "Malaysia", "twin"],
  "Ho Chi Minh": ["Vietnam", "motorbikes", "Saigon"],
  "Hanoi":       ["Vietnam", "capital", "old quarter"],
  "Rio de Janeiro":["carnival", "Brazil", "beach"],
  "Lima":        ["Peru", "Pacific", "ceviche"],
  "Bogota":      ["Colombia", "mountains", "coffee"],
  "Santiago":    ["Chile", "Andes", "long country"],
  "Havana":      ["Cuba", "vintage cars", "cigars"],
  "Reykjavik":   ["Iceland", "aurora", "small"],
  "Oslo":        ["Norway", "fjords", "expensive"],
  "Stockholm":   ["Sweden", "islands", "IKEA"],
  "Copenhagen":  ["Denmark", "bikes", "hygge"],
  "Helsinki":    ["Finland", "design", "cold"],

  // ── 🧠 Emotions ──────────────────────────────────────────────────────────────
  "happy":       ["smile", "joy", "positive"],
  "sad":         ["cry", "blue", "tears"],
  "angry":       ["mad", "red", "shout"],
  "scared":      ["fear", "shake", "run"],
  "surprised":   ["shock", "wide eyes", "unexpected"],
  "nervous":     ["sweat", "butterflies", "shake"],
  "excited":     ["jump", "energy", "can't wait"],
  "bored":       ["yawn", "nothing to do", "empty"],
  "confused":    ["lost", "scratch head", "question mark"],
  "proud":       ["chest out", "achievement", "tall"],
  "embarrassed": ["red face", "awkward", "hide"],
  "jealous":     ["want", "envy", "green"],
  "lonely":      ["alone", "empty", "missing people"],
  "grateful":    ["thank you", "appreciate", "blessed"],
  "hopeful":     ["optimistic", "wish", "bright"],
  "anxious":     ["worry", "chest tight", "what if"],
  "relaxed":     ["calm", "breathe", "no stress"],
  "frustrated":  ["blocked", "stuck", "irritated"],
  "disgusted":   ["gross", "eww", "turn away"],
  "guilty":      ["wrong", "regret", "shame"],
  "love":        ["heart", "warm", "care"],
  "hate":        ["strong dislike", "anger", "avoid"],
  "fear":        ["scared", "danger", "hide"],
  "joy":         ["happy", "light", "laugh"],
  "grief":       ["loss", "deep sad", "cry"],
  "shame":       ["wrong", "hide", "embarrassed"],
  "regret":      ["wish I hadnt", "past", "if only"],
  "trust":       ["believe", "safe", "faith"],
  "doubt":       ["unsure", "question", "hesitate"],
  "wonder":      ["amazed", "curious", "wow"],
  "nostalgia":   ["old memories", "past", "bittersweet"],
  "hope":        ["future", "wish", "positive"],
  "despair":     ["no hope", "dark", "give up"],
  "envy":        ["want what others have", "jealous", "covet"],
  "relief":      ["phew", "safe now", "relax"],
  "shock":       ["sudden", "gasp", "freeze"],
  "calm":        ["peace", "quiet", "still"],
  "rage":        ["extreme anger", "explode", "red"],
  "panic":       ["can't breathe", "run", "emergency"],
  "content":     ["satisfied", "enough", "peaceful"],
  "inspired":    ["motivated", "creative", "driven"],
  "tired":       ["sleepy", "heavy eyes", "yawn"],
  "overwhelmed": ["too much", "can't cope", "drown"],
  "curious":     ["want to know", "explore", "question"],
  "confident":   ["sure", "strong", "believe in self"],
  "heartbroken": ["pain", "love lost", "cry"],
  "homesick":    ["miss home", "far away", "family"],
  "missing someone":["absence", "thinking of", "lonely"],
  "in love":     ["butterflies", "can't stop thinking", "heart"],
  "betrayed":    ["trust broken", "backstabbed", "hurt"],

  // ── 🎨 Artists ───────────────────────────────────────────────────────────────
  "Leonardo da Vinci":["Mona Lisa", "inventor", "Renaissance"],
  "Picasso":     ["cubism", "Spain", "abstract faces"],
  "Van Gogh":    ["Starry Night", "ear", "yellow"],
  "Michelangelo":["Sistine Chapel", "sculptor", "David"],
  "Rembrandt":   ["dark portraits", "Netherlands", "light"],
  "Frida Kahlo": ["Mexico", "self portrait", "unibrow"],
  "Andy Warhol": ["pop art", "Campbell's soup", "Marilyn"],
  "Salvador Dali":["melting clocks", "surrealism", "mustache"],
  "Claude Monet":["water lilies", "impressionism", "France"],
  "Banksy":      ["street art", "anonymous", "graffiti"],
  "Beyoncé":     ["Single Ladies", "Queen Bey", "Destiny's Child"],
  "Michael Jackson":["King of Pop", "Thriller", "moonwalk"],
  "Taylor Swift":["Swifties", "country pop", "albums"],
  "Ed Sheeran":  ["Shape of You", "ginger", "guitar"],
  "Adele":       ["Hello", "powerful voice", "British"],
  "Eminem":      ["Slim Shady", "rap", "Detroit"],
  "Drake":       ["OVO", "Toronto", "rap"],
  "Rihanna":     ["Barbados", "Fenty", "pop"],
  "Lady Gaga":   ["meat dress", "poker face", "theatrical"],
  "Bruno Mars":  ["funk", "smooth", "Hawaii"],
  "BTS":         ["K-pop", "Korea", "ARMY"],
  "Blackpink":   ["K-pop", "Korea", "girl group"],
  "Bad Bunny":   ["reggaeton", "Puerto Rico", "Latin"],
  "The Weeknd":  ["Blinding Lights", "R&B", "sunglasses"],
  "Billie Eilish":["whisper voice", "green hair", "young"],
  "Harry Styles":["One Direction", "fashion", "British"],
  "Dua Lipa":    ["Levitating", "dance pop", "Albanian"],
  "Ariana Grande":["high ponytail", "pop", "powerful voice"],
  "Justin Bieber":["Baby", "Canadian", "teen pop"],
  "Shakira":     ["hips", "Waka Waka", "Colombian"],
  "Kendrick Lamar":["Compton", "rap", "Pulitzer"],
  "Kanye West":  ["rap", "Yeezy", "controversial"],
  "Jay-Z":       ["rap", "New York", "Beyoncé's husband"],
  "Coldplay":    ["Yellow", "British", "colorful concerts"],
  "Radiohead":   ["Creep", "British", "alternative"],
  "Bob Marley":  ["reggae", "Jamaica", "dreadlocks"],
  "Elvis Presley":["rock and roll", "hip shake", "Vegas"],
  "David Bowie": ["Ziggy Stardust", "glam", "chameleon"],
  "Freddie Mercury":["Queen", "We Will Rock You", "mustache"],
  "Madonna":     ["pop queen", "Material Girl", "reinvention"],
  "The Beatles": ["Fab Four", "Liverpool", "John Lennon"],
  "Rolling Stones":["Mick Jagger", "rock", "tongue logo"],
  "ABBA":        ["Sweden", "Dancing Queen", "disco"],
  "Elton John":  ["piano", "glasses", "Rocket Man"],
  "Frank Sinatra":["My Way", "jazz", "Rat Pack"],
  "Whitney Houston":["I Will Always Love You", "powerful voice", "US"],
  "Mariah Carey":["whistle notes", "Christmas", "diva"],
  "Celine Dion": ["Titanic song", "Canada", "powerful"],
  "Stevie Wonder":["blind", "harmonica", "soul"],
  "Prince":      ["Purple Rain", "Minneapolis", "musician"],
};
