// Pre-generated hints for every word in the word bank.
// Each word maps to 3 closely associated clue words the imposter can use to blend in.

const HINTS = {

  // ── 🐾 Animals ──────────────────────────────────────────────────────────────────
  "elephant":    ["trunk", "ivory", "savanna"],
  "penguin":     ["tuxedo", "Antarctic", "waddle"],
  "dolphin":     ["echo", "flipper", "ocean"],
  "chameleon":   ["camouflage", "color", "lizard"],
  "cobra":       ["venom", "hood", "strike"],
  "panda":       ["bamboo", "China", "black-white"],
  "cheetah":     ["sprint", "spots", "savanna"],
  "octopus":     ["tentacles", "ink", "eight"],
  "flamingo":    ["pink", "wading", "one-legged"],
  "gorilla":     ["silverback", "jungle", "strength"],
  "jaguar":      ["spots", "Amazon", "ambush"],
  "koala":       ["eucalyptus", "marsupial", "Australia"],
  "narwhal":     ["tusk", "Arctic", "unicorn"],
  "capybara":    ["rodent", "semi-aquatic", "South America"],
  "axolotl":     ["gills", "Mexico", "regenerate"],
  "platypus":    ["bill", "venomous", "egg-laying"],
  "meerkat":     ["sentinel", "burrow", "Kalahari"],
  "wolverine":   ["claws", "fierce", "boreal"],
  "tapir":       ["snout", "rainforest", "odd-toed"],
  "okapi":       ["stripes", "Congo", "giraffe-relative"],
  "manatee":     ["sea cow", "gentle", "shallow water"],
  "pangolin":    ["scales", "ant-eater", "roll"],
  "armadillo":   ["shell", "burrowing", "Texas"],
  "cassowary":   ["casque", "dangerous", "rainforest"],
  "wombat":      ["burrowing", "Australia", "cubic scat"],
  "hyena":       ["laugh", "scavenger", "Africa"],
  "lynx":        ["tufted ears", "snow", "stealthy"],
  "caracal":     ["ear tufts", "leap", "Africa"],
  "serval":      ["spots", "long legs", "grassland"],
  "ocelot":      ["spots", "nocturnal", "jungle"],
  "albatross":   ["wingspan", "soar", "ocean"],
  "condor":      ["wingspan", "Andes", "vulture"],
  "pelican":     ["pouch", "fish", "coastal"],
  "toucan":      ["beak", "colorful", "tropical"],
  "macaw":       ["parrot", "colorful", "Amazon"],
  "piranha":     ["teeth", "Amazon", "school"],
  "barracuda":   ["teeth", "reef", "torpedo"],
  "manta ray":   ["flat", "filter feeder", "ocean"],
  "hammerhead":  ["T-shaped head", "shark", "reef"],
  "stingray":    ["barb", "flat", "sandy floor"],
  "komodo dragon":["venom", "Indonesia", "large lizard"],
  "iguana":      ["spines", "tropical", "herbivore"],
  "gecko":       ["sticky feet", "nocturnal", "wall-climber"],
  "salamander":  ["moist", "amphibian", "regenerate"],
  "bison":       ["herd", "prairie", "shaggy"],
  "wildebeest":  ["migration", "Africa", "horns"],
  "caribou":     ["migration", "antlers", "Arctic"],
  "moose":       ["antlers", "North America", "tall"],
  "ibex":        ["curved horns", "mountain", "Alpine"],

  // ── 🍕 Food & Drinks ────────────────────────────────────────────────────────
  "sushi":       ["rice", "raw fish", "Japan"],
  "burrito":     ["tortilla", "beans", "Mexico"],
  "tiramisu":    ["espresso", "mascarpone", "ladyfingers"],
  "croissant":   ["butter", "flaky", "France"],
  "ramen":       ["noodles", "broth", "Japan"],
  "fondue":      ["melted cheese", "dipping", "Switzerland"],
  "paella":      ["saffron", "rice", "Spain"],
  "dim sum":     ["dumplings", "steamer", "Cantonese"],
  "gelato":      ["Italian ice cream", "dense", "creamy"],
  "baklava":     ["phyllo", "honey", "pistachio"],
  "gyoza":       ["dumpling", "pan-fried", "Japan"],
  "hummus":      ["chickpeas", "tahini", "Middle East"],
  "boba":        ["tapioca", "milk tea", "Taiwan"],
  "pho":         ["beef broth", "Vietnam", "noodles"],
  "ceviche":     ["lime", "raw fish", "Peru"],
  "risotto":     ["arborio", "creamy", "Italy"],
  "tagine":      ["slow-cooked", "Morocco", "clay pot"],
  "biryani":     ["basmati", "spiced", "India"],
  "goulash":     ["paprika", "beef stew", "Hungary"],
  "pierogi":     ["dumpling", "Poland", "potato"],
  "kimchi":      ["fermented", "cabbage", "Korea"],
  "tempura":     ["battered", "fried", "Japan"],
  "satay":       ["skewer", "peanut sauce", "Southeast Asia"],
  "falafel":     ["chickpeas", "fried", "Middle East"],
  "shakshuka":   ["eggs", "tomato", "Middle East"],
  "chimichanga": ["fried burrito", "Arizona", "crispy"],
  "empanada":    ["pastry", "stuffed", "Latin America"],
  "arepa":       ["corn cake", "Colombia", "stuffed"],
  "injera":      ["spongy", "Ethiopia", "flatbread"],
  "borscht":     ["beet", "Eastern Europe", "soup"],
  "moussaka":    ["eggplant", "lamb", "Greece"],
  "spanakopita": ["spinach", "phyllo", "Greece"],
  "ratatouille": ["vegetables", "Provence", "stew"],
  "bouillabaisse":["fish stew", "Marseille", "saffron"],
  "cassoulet":   ["white beans", "duck", "France"],
  "poutine":     ["fries", "gravy", "cheese curds"],
  "shawarma":    ["rotisserie", "wrap", "Middle East"],
  "kebab":       ["skewer", "grilled", "Middle East"],
  "yakitori":    ["grilled chicken", "skewer", "Japan"],
  "bulgogi":     ["marinated beef", "Korea", "grilled"],
  "laksa":       ["coconut", "noodle soup", "Malaysia"],
  "rendang":     ["dry curry", "Indonesia", "beef"],
  "nasi goreng": ["fried rice", "Indonesia", "egg"],
  "pad thai":    ["stir-fried noodles", "Thailand", "peanuts"],
  "massaman":    ["curry", "peanuts", "Thailand"],
  "espresso":    ["shot", "coffee", "Italy"],
  "matcha":      ["green tea", "Japan", "powder"],
  "horchata":    ["rice milk", "cinnamon", "Mexico"],
  "lassi":       ["yogurt drink", "India", "mango"],
  "kombucha":    ["fermented", "tea", "probiotic"],

  // ── ⚽ Sports ────────────────────────────────────────────────────────────────
  "surfing":     ["waves", "board", "ocean"],
  "fencing":     ["épée", "lunge", "mask"],
  "archery":     ["bow", "target", "quiver"],
  "curling":     ["broom", "ice", "stone"],
  "lacrosse":    ["stick", "net", "Canada"],
  "handball":    ["court", "goal", "throw"],
  "squash":      ["racket", "small court", "rubber ball"],
  "biathlon":    ["skiing", "rifle", "Nordic"],
  "javelin":     ["throw", "spear", "track"],
  "discus":      ["spinning", "throw", "Olympics"],
  "bobsled":     ["sled", "track", "team"],
  "wrestling":   ["grapple", "mat", "pin"],
  "skeleton":    ["sled", "head-first", "ice track"],
  "polo":        ["horse", "mallet", "field"],
  "rowing":      ["oar", "boat", "stroke"],
  "weightlifting":["barbell", "clean jerk", "snatch"],
  "judo":        ["throw", "gi", "Japan"],
  "taekwondo":   ["kicks", "Korea", "belt"],
  "karate":      ["kata", "chop", "dojo"],
  "aikido":      ["redirection", "Japan", "harmony"],
  "triathlon":   ["swim bike run", "endurance", "transition"],
  "pentathlon":  ["five events", "Olympic", "fencing"],
  "decathlon":   ["ten events", "Olympic", "track"],
  "heptathlon":  ["seven events", "women", "track"],
  "steeplechase":["hurdles", "water jump", "track"],
  "moguls":      ["bumps", "skiing", "aerial"],
  "slalom":      ["gates", "skiing", "zigzag"],
  "halfpipe":    ["snowboard", "aerial", "U-shape"],
  "luge":        ["sled", "feet-first", "ice"],
  "synchronized swimming":["pool", "routine", "team"],
  "water polo":  ["pool", "ball", "goal"],
  "canoe":       ["paddle", "river", "pointed"],
  "kayak":       ["double paddle", "sit-in", "water"],
  "sailing":     ["wind", "boat", "keel"],
  "rock climbing":["harness", "holds", "route"],
  "parkour":     ["urban", "free running", "obstacles"],
  "skateboarding":["tricks", "halfpipe", "deck"],
  "BMX":         ["bike", "dirt jumps", "tricks"],
  "motocross":   ["dirt bike", "jumps", "circuit"],
  "dressage":    ["horse", "precision", "choreography"],
  "equestrian":  ["horse", "riding", "jumping"],
  "snooker":     ["cue", "billiards", "reds"],
  "darts":       ["bullseye", "board", "throw"],
  "bowls":       ["lawn", "jack", "bias"],
  "badminton":   ["shuttlecock", "racket", "net"],
  "table tennis":["paddle", "spin", "net"],
  "racquetball": ["enclosed court", "racket", "ball"],
  "croquet":     ["mallet", "hoop", "lawn"],
  "kabaddi":     ["tag", "India", "breath"],

  // ── 🎬 Movies & TV ──────────────────────────────────────────────────────────
  "inception":   ["dreams", "spinning top", "DiCaprio"],
  "matrix":      ["red pill", "simulation", "Neo"],
  "avatar":      ["Pandora", "Na'vi", "blue"],
  "parasite":    ["class", "Korea", "basement"],
  "joker":       ["clown", "Gotham", "chaos"],
  "dunkirk":     ["WWII", "evacuation", "beach"],
  "arrival":     ["aliens", "language", "heptapods"],
  "interstellar":["black hole", "space", "time dilation"],
  "gravity":     ["space", "orbit", "Sandra Bullock"],
  "dune":        ["desert", "spice", "sandworm"],
  "oppenheimer": ["atomic bomb", "Manhattan", "Nolan"],
  "barbie":      ["Mattel", "pink", "Malibu"],
  "titanic":     ["iceberg", "ship", "sinking"],
  "gladiator":   ["Rome", "arena", "Russell Crowe"],
  "frozen":      ["ice queen", "Elsa", "Arendelle"],
  "whiplash":    ["drums", "jazz", "intense teacher"],
  "moonlight":   ["identity", "Florida", "coming of age"],
  "nomadland":   ["van", "American West", "Frances McDormand"],
  "spotlight":   ["journalism", "church", "investigation"],
  "hereditary":  ["grief", "horror", "family"],
  "midsommar":   ["Sweden", "cult", "summer solstice"],
  "annihilation":["mutation", "Area X", "lighthouse"],
  "ex machina":  ["AI", "robot", "consciousness"],
  "tenet":       ["time reversal", "spy", "entropy"],
  "prestige":    ["magic", "rivalry", "obsession"],
  "memento":     ["memory", "tattoos", "backward"],
  "mulholland":  ["Hollywood", "mystery", "Lynch"],
  "vertigo":     ["fear of heights", "Hitchcock", "obsession"],
  "psycho":      ["shower", "motel", "Hitchcock"],
  "casablanca":  ["WWII", "Rick", "Humphrey Bogart"],
  "chinatown":   ["noir", "water", "Jack Nicholson"],
  "goodfellas":  ["mafia", "Scorsese", "Ray Liotta"],
  "fargo":       ["wood chipper", "Minnesota", "accents"],
  "pulp fiction":["briefcase", "Tarantino", "nonlinear"],
  "shining":     ["hotel", "twins", "Jack Nicholson"],
  "alien":       ["xenomorph", "space", "Sigourney Weaver"],
  "blade runner":["replicants", "noir", "neon rain"],
  "metropolis":  ["silent film", "robot", "dystopia"],
  "brazil":      ["bureaucracy", "dystopia", "Terry Gilliam"],
  "breaking bad":["meth", "chemistry teacher", "Albuquerque"],
  "sopranos":    ["mob boss", "New Jersey", "therapy"],
  "wire":        ["Baltimore", "drug war", "police"],
  "succession":  ["media empire", "wealth", "family drama"],
  "chernobyl":   ["nuclear disaster", "Soviet", "HBO"],
  "westworld":   ["robots", "Wild West", "consciousness"],
  "dark":        ["time travel", "German", "caves"],
  "severance":   ["work-life", "memory split", "Lumon"],
  "euphoria":    ["teens", "drugs", "Zendaya"],
  "squid game":  ["survival", "Korea", "childhood games"],

  // ── 💻 Technology ────────────────────────────────────────────────────────────
  "blockchain":  ["ledger", "decentralized", "crypto"],
  "algorithm":   ["steps", "logic", "computation"],
  "satellite":   ["orbit", "signal", "GPS"],
  "transistor":  ["switching", "semiconductor", "tiny"],
  "compiler":    ["translate", "source code", "binary"],
  "bandwidth":   ["data rate", "pipe", "megabits"],
  "firmware":    ["embedded", "ROM", "device"],
  "kernel":      ["OS core", "system calls", "Linux"],
  "router":      ["network", "packets", "gateway"],
  "server":      ["host", "request", "rack"],
  "socket":      ["connection", "port", "network"],
  "token":       ["authentication", "session", "JWT"],
  "protocol":    ["rules", "handshake", "TCP"],
  "interface":   ["API", "boundary", "contract"],
  "pixel":       ["display", "smallest unit", "resolution"],
  "encryption":  ["cipher", "key", "secure"],
  "database":    ["tables", "query", "storage"],
  "variable":    ["value", "declaration", "store"],
  "recursion":   ["self-reference", "base case", "stack"],
  "hypervisor":  ["virtual machine", "host", "type 1"],
  "container":   ["Docker", "isolated", "image"],
  "microservice":["small", "API", "distributed"],
  "webhook":     ["callback", "HTTP", "event"],
  "endpoint":    ["URL", "API", "route"],
  "latency":     ["delay", "ping", "milliseconds"],
  "throughput":  ["data rate", "capacity", "bandwidth"],
  "checksum":    ["hash", "verify", "integrity"],
  "payload":     ["data body", "request", "content"],
  "handshake":   ["TCP", "connection", "negotiate"],
  "sandbox":     ["isolated", "test", "environment"],
  "runtime":     ["execution", "live", "environment"],
  "debugger":    ["breakpoint", "inspect", "bug"],
  "refactor":    ["clean up", "restructure", "code"],
  "deployment":  ["ship", "production", "release"],
  "authentication":["login", "identity", "verify"],
  "authorization":["permissions", "access", "role"],
  "middleware":  ["pipeline", "layer", "process"],
  "pipeline":    ["stages", "CI/CD", "flow"],
  "cache":       ["fast storage", "memory", "hit"],
  "repository":  ["git", "code storage", "branch"],
  "branch":      ["git", "feature", "fork"],
  "commit":      ["git", "snapshot", "message"],
  "merge":       ["combine", "pull request", "conflict"],
  "rollback":    ["revert", "undo deploy", "previous"],
  "neural network":["deep learning", "layers", "weights"],
  "gradient":    ["slope", "descent", "backprop"],
  "tensor":      ["multi-dimensional", "array", "PyTorch"],
  "cluster":     ["group", "nodes", "Kubernetes"],
  "node":        ["network point", "server", "graph"],

  // ── 🌿 Nature ────────────────────────────────────────────────────────────────
  "glacier":     ["ice", "slow-moving", "meltwater"],
  "volcano":     ["lava", "eruption", "magma"],
  "monsoon":     ["seasonal rain", "Asia", "flooding"],
  "aurora":      ["Northern Lights", "sky", "solar wind"],
  "canyon":      ["gorge", "Colorado River", "carved"],
  "stalactite":  ["cave", "hanging", "limestone"],
  "geyser":      ["Yellowstone", "steam", "eruption"],
  "fjord":       ["Norway", "glacier-carved", "inlet"],
  "tundra":      ["frozen", "treeless", "Arctic"],
  "mangrove":    ["coastal", "roots", "saltwater"],
  "lagoon":      ["shallow", "reef", "calm water"],
  "plateau":     ["flat-topped", "elevated", "mesa"],
  "savanna":     ["grassland", "Africa", "acacia"],
  "delta":       ["river mouth", "sediment", "fan-shaped"],
  "archipelago": ["island chain", "ocean", "scattered"],
  "atoll":       ["coral ring", "lagoon", "Pacific"],
  "mesa":        ["flat top", "desert", "Southwest"],
  "butte":       ["isolated tower", "desert", "flat top"],
  "caldera":     ["volcanic crater", "collapsed", "lake"],
  "escarpment":  ["cliff face", "steep", "eroded"],
  "permafrost":  ["frozen ground", "Arctic", "methane"],
  "moraine":     ["glacial debris", "ridge", "ice"],
  "watershed":   ["drainage basin", "divide", "rivers"],
  "tributary":   ["smaller river", "joins", "stream"],
  "estuary":     ["river mouth", "brackish", "tidal"],
  "bog":         ["wet peat", "sphagnum", "waterlogged"],
  "fen":         ["wetland", "alkaline", "peat"],
  "mire":        ["swampy", "boggy", "soft ground"],
  "taiga":       ["boreal forest", "conifers", "Siberia"],
  "chaparral":   ["shrubland", "California", "fire-adapted"],
  "steppe":      ["dry grassland", "Eurasia", "flat"],
  "pampas":      ["Argentine grassland", "cattle", "flat"],
  "veldt":       ["South Africa", "grassland", "open"],
  "karst":       ["limestone", "caves", "sinkholes"],
  "sinkhole":    ["collapse", "limestone", "sudden"],
  "spring":      ["freshwater", "ground source", "bubbling"],
  "gully":       ["erosion channel", "rain", "small ravine"],
  "ravine":      ["narrow valley", "stream", "steep"],
  "gorge":       ["deep canyon", "river-carved", "walls"],
  "bluff":       ["cliff face", "river bank", "steep"],
  "coral":       ["reef", "skeleton", "marine"],
  "kelp":        ["seaweed", "forest", "cold water"],
  "plankton":    ["microscopic", "ocean", "base of food chain"],
  "spore":       ["fungus", "reproduction", "tiny"],
  "mycelium":    ["fungal network", "underground", "threads"],
  "bioluminescence":["glow", "deep sea", "chemical light"],
  "thermocline": ["ocean layer", "temperature boundary", "diving"],
  "solstice":    ["longest day", "sun", "seasonal"],
  "equinox":     ["equal day night", "spring autumn", "sun"],

  // ── 💼 Occupations ──────────────────────────────────────────────────────────
  "surgeon":     ["scalpel", "operating room", "incision"],
  "architect":   ["blueprints", "design", "structures"],
  "astronaut":   ["space", "rocket", "weightless"],
  "sommelier":   ["wine", "tasting", "cellar"],
  "cartographer":["maps", "charting", "geography"],
  "archaeologist":["excavation", "artifacts", "history"],
  "taxidermist": ["stuffing", "preserve", "animals"],
  "actuary":     ["risk", "statistics", "insurance"],
  "mortician":   ["funeral", "embalm", "burial"],
  "curator":     ["museum", "collection", "exhibition"],
  "locksmith":   ["keys", "locks", "pick"],
  "blacksmith":  ["forge", "anvil", "iron"],
  "archivist":   ["documents", "preserve", "records"],
  "mediator":    ["conflict", "neutral", "settlement"],
  "conductor":   ["baton", "orchestra", "podium"],
  "stenographer":["shorthand", "court", "dictation"],
  "podiatrist":  ["feet", "toenails", "clinic"],
  "orthodontist":["braces", "teeth", "alignment"],
  "radiologist": ["X-ray", "scan", "diagnosis"],
  "anesthesiologist":["sedation", "surgery", "pain"],
  "metallurgist":["metals", "alloys", "smelting"],
  "geologist":   ["rocks", "strata", "field work"],
  "seismologist":["earthquakes", "seismic", "Richter"],
  "volcanologist":["lava", "eruption", "fieldwork"],
  "oceanographer":["sea", "research", "depth"],
  "cryptographer":["ciphers", "encryption", "codes"],
  "etymologist": ["word origins", "linguistics", "roots"],
  "numismatist": ["coins", "collecting", "currency"],
  "philatelist": ["stamps", "collecting", "postmarks"],
  "ornithologist":["birds", "binoculars", "species"],
  "entomologist":["insects", "specimens", "field"],
  "mycologist":  ["fungi", "mushrooms", "spores"],
  "herpetologist":["reptiles", "amphibians", "fieldwork"],
  "ichthyologist":["fish", "marine", "taxonomy"],
  "malacologist":["mollusks", "shells", "invertebrates"],
  "glazier":     ["glass", "windows", "cutting"],
  "cooper":      ["barrels", "wooden", "casks"],
  "fletcher":    ["arrows", "feathers", "archery"],
  "chandler":    ["candles", "wax", "wick"],
  "millwright":  ["mills", "machinery", "installation"],
  "farrier":     ["horseshoes", "forge", "hooves"],
  "saddler":     ["saddles", "leather", "horse"],
  "tanner":      ["leather", "hides", "chemicals"],
  "cobbler":     ["shoes", "sole", "repair"],
  "hatter":      ["hats", "felt", "millinery"],
  "docent":      ["museum", "tour guide", "education"],
  "notary":      ["documents", "seal", "legal"],
  "bailiff":     ["court", "security", "officer"],
  "surveyor":    ["land", "measurement", "boundaries"],
  "appraiser":   ["valuation", "property", "estimate"],

  // ── ✈️ Travel ────────────────────────────────────────────────────────────────
  "passport":    ["border", "stamp", "identity"],
  "hostel":      ["bunk beds", "backpackers", "shared"],
  "layover":     ["airport wait", "connecting flight", "transit"],
  "customs":     ["border", "declaration", "inspection"],
  "concierge":   ["hotel desk", "recommendations", "service"],
  "itinerary":   ["schedule", "plan", "trip"],
  "excursion":   ["day trip", "guided", "sightseeing"],
  "boarding":    ["gate", "plane", "pass"],
  "carousel":    ["luggage", "baggage claim", "belt"],
  "terminal":    ["airport", "gate", "departure"],
  "departure":   ["gate", "flight", "leaving"],
  "charter":     ["private plane", "group flight", "booked"],
  "transit":     ["transfer", "passing through", "hub"],
  "souvenir":    ["keepsake", "gift shop", "memory"],
  "jetlag":      ["time zones", "fatigue", "flying"],
  "backpacking": ["rucksack", "hostel", "budget"],
  "pilgrimage":  ["sacred", "religious journey", "shrine"],
  "expedition":  ["exploration", "remote", "team"],
  "safari":      ["wildlife", "Africa", "jeep"],
  "cruise":      ["ship", "ocean", "port"],
  "immigration": ["visa", "border", "entry"],
  "quarantine":  ["isolation", "disease", "border"],
  "embargo":     ["ban", "trade", "restriction"],
  "contraband":  ["smuggling", "illegal", "seized"],
  "declaration": ["customs form", "declare", "duty"],
  "boutique hotel":["small", "unique", "luxury"],
  "villa":       ["rental", "pool", "Mediterranean"],
  "bungalow":    ["single story", "tropical", "porch"],
  "campsite":    ["tent", "outdoors", "fire pit"],
  "glamping":    ["luxury camping", "tent", "comfort"],
  "overland":    ["road trip", "border crossing", "Africa"],
  "hitchhike":   ["roadside", "thumb", "stranger"],
  "interrail":   ["Europe", "train pass", "backpacker"],
  "stopover":    ["brief stay", "layover city", "transit"],
  "connection":  ["transfer", "next flight", "airport"],
  "landmark":    ["famous sight", "monument", "photo spot"],
  "monument":    ["historic", "stone", "memorial"],
  "heritage site":["UNESCO", "preserved", "historical"],
  "ruins":       ["ancient", "crumbled", "archaeological"],
  "cathedral":   ["Gothic", "spire", "sacred"],
  "bazaar":      ["market", "Middle East", "stalls"],
  "marketplace": ["vendors", "open air", "trade"],
  "plaza":       ["square", "central", "fountain"],
  "promenade":   ["seafront walk", "path", "leisurely"],
  "waterfront":  ["harbor", "dockside", "view"],
  "visa":        ["entry permit", "embassy", "stamp"],
  "embassy":     ["diplomatic", "consulate", "foreign"],
  "consulate":   ["visa", "citizens abroad", "diplomatic"],
  "exchange rate":["currency", "conversion", "forex"],
  "travel insurance":["medical", "trip cancellation", "coverage"],

  // ── 🎵 Music ─────────────────────────────────────────────────────────────────
  "vinyl":       ["record", "turntable", "groove"],
  "bassline":    ["rhythm", "low frequency", "groove"],
  "chorus":      ["hook", "repeat", "loudest part"],
  "symphony":    ["orchestra", "movements", "classical"],
  "acoustic":    ["unplugged", "natural", "guitar"],
  "drumroll":    ["snare", "anticipation", "percussion"],
  "falsetto":    ["high voice", "head voice", "register"],
  "interlude":   ["break", "bridge", "middle section"],
  "melody":      ["tune", "notes", "hum"],
  "tempo":       ["speed", "BPM", "beat"],
  "arpeggio":    ["broken chord", "ascending", "notes"],
  "cadence":     ["resolution", "phrase end", "rhythm"],
  "crescendo":   ["getting louder", "build-up", "peak"],
  "diminuendo":  ["getting quieter", "fade", "soften"],
  "fortissimo":  ["very loud", "dynamic", "forte"],
  "tremolo":     ["rapid repetition", "vibration", "string"],
  "vibrato":     ["wavering pitch", "singer", "expressive"],
  "pizzicato":   ["plucked strings", "technique", "staccato"],
  "staccato":    ["short notes", "detached", "crisp"],
  "legato":      ["smooth", "connected", "flowing"],
  "overture":    ["opening piece", "opera", "introduction"],
  "sonata":      ["classical form", "piano", "movements"],
  "concerto":    ["soloist", "orchestra", "three movements"],
  "requiem":     ["mass for the dead", "Mozart", "solemn"],
  "nocturne":    ["night piece", "Chopin", "piano"],
  "ballad":      ["story song", "slow", "emotional"],
  "serenade":    ["evening song", "romance", "outdoor"],
  "anthem":      ["national", "hymn", "crowd"],
  "jingle":      ["ad", "catchy", "commercial"],
  "lullaby":     ["bedtime", "soft", "baby"],
  "riff":        ["guitar hook", "repeated phrase", "rock"],
  "hook":        ["catchy phrase", "earworm", "chorus"],
  "bridge":      ["contrasting section", "transition", "song"],
  "breakdown":   ["stripped back", "rhythm", "drop"],
  "drop":        ["bass heavy", "EDM", "peak"],
  "reverb":      ["echo", "space", "effect"],
  "distortion":  ["guitar effect", "fuzz", "overdrive"],
  "compression": ["dynamic range", "level", "mastering"],
  "equalization":["EQ", "frequencies", "mixing"],
  "mastering":   ["final mix", "polish", "release"],
  "turntable":   ["vinyl", "DJ", "needle"],
  "synthesizer": ["electronic", "keys", "oscillator"],
  "theremin":    ["no-touch", "eerie", "sci-fi"],
  "harpsichord": ["plucked", "Baroque", "keyboard"],
  "sitar":       ["India", "strings", "Ravi Shankar"],
  "didgeridoo":  ["Australia", "circular breathing", "drone"],
  "marimba":     ["wooden keys", "mallets", "percussion"],
  "dulcimer":    ["Appalachian", "strings", "mountain"],
  "zither":      ["strings", "flat", "folk"],
  "hurdy-gurdy": ["rotating wheel", "drone", "medieval"],

  // ── 🎮 Video Games ───────────────────────────────────────────────────────────
  "respawn":     ["re-enter", "after death", "spawn point"],
  "dungeon":     ["underground", "enemies", "RPG"],
  "loot":        ["dropped items", "treasure", "chest"],
  "checkpoint":  ["save point", "progress", "autosave"],
  "glitch":      ["bug", "exploit", "unintended"],
  "speedrun":    ["fastest time", "record", "any%"],
  "tutorial":    ["beginner", "learn controls", "intro"],
  "inventory":   ["items", "bag", "carry"],
  "sandbox":     ["open world", "freedom", "Minecraft"],
  "boss":        ["final enemy", "health bar", "difficult"],
  "crafting":    ["combine items", "recipe", "resources"],
  "farming":     ["repeat grinding", "resources", "loop"],
  "grinding":    ["repetitive", "XP gain", "level up"],
  "raiding":     ["group content", "boss fight", "guild"],
  "PvP":         ["player vs player", "competitive", "arena"],
  "DLC":         ["extra content", "paid", "expansion"],
  "patch":       ["update", "fix bugs", "nerf"],
  "nerf":        ["weaken", "balance change", "patch"],
  "buff":        ["strengthen", "power up", "boost"],
  "meta":        ["best strategy", "current dominant", "tier list"],
  "hitbox":      ["collision area", "pixel perfect", "fighting"],
  "cooldown":    ["wait time", "ability", "recharge"],
  "aggro":       ["enemy attention", "threat", "tank"],
  "tank":        ["absorbs damage", "frontline", "shield"],
  "healer":      ["restore HP", "support", "medic"],
  "permadeath":  ["no respawn", "roguelike", "one life"],
  "roguelike":   ["procedural", "permadeath", "dungeon"],
  "procedural":  ["random generated", "algorithm", "unique"],
  "open world":  ["explore freely", "sandbox", "vast map"],
  "cutscene":    ["cinematic", "non-interactive", "story"],
  "achievement": ["unlock", "trophy", "milestone"],
  "trophy":      ["PlayStation", "unlock", "platinum"],
  "leaderboard": ["rankings", "high score", "competitive"],
  "matchmaking": ["pairing players", "MMR", "queue"],
  "ping":        ["latency", "ms", "connection"],
  "narrative":   ["story", "plot", "lore"],
  "dialogue":    ["conversation", "NPCs", "text box"],
  "branching":   ["choices", "multiple endings", "decision"],
  "morality":    ["good evil", "alignment", "karma"],
  "reputation":  ["faction", "standing", "karma"],
  "side quest":  ["optional", "NPC mission", "extra"],
  "main quest":  ["story mission", "campaign", "primary"],
  "fast travel": ["teleport", "map", "quick move"],
  "waypoint":    ["marker", "map pin", "navigate"],
  "minimap":     ["HUD", "small map", "radar"],
  "controller":  ["gamepad", "analog stick", "buttons"],
  "emulator":    ["mimic hardware", "retro", "PC"],
  "modding":     ["user mods", "community", "customize"],
  "overclocking":["speed up", "hardware", "heat"],
  "frame rate":  ["FPS", "smooth", "60fps"],

  // ── 🧪 Science ───────────────────────────────────────────────────────────────
  "mitosis":     ["cell division", "chromosomes", "two cells"],
  "neutron":     ["neutral charge", "nucleus", "atomic"],
  "catalyst":    ["speed up reaction", "enzyme", "unchanged"],
  "molecule":    ["atoms bonded", "compound", "H2O"],
  "gravity":     ["mass attraction", "orbit", "Newton"],
  "orbit":       ["circular path", "gravity", "satellite"],
  "genome":      ["DNA sequence", "all genes", "map"],
  "photon":      ["light particle", "quantum", "wave"],
  "erosion":     ["wearing away", "water wind", "sediment"],
  "membrane":    ["cell wall", "barrier", "permeable"],
  "osmosis":     ["water through membrane", "concentration", "diffusion"],
  "diffusion":   ["spreading out", "concentration gradient", "particles"],
  "synthesis":   ["combine", "create", "chemical"],
  "oxidation":   ["oxygen gain", "rust", "electron loss"],
  "reduction":   ["electron gain", "opposite oxidation", "redox"],
  "hypothesis":  ["testable idea", "prediction", "experiment"],
  "variable":    ["factor", "controlled", "independent"],
  "control":     ["baseline", "unchanged", "comparison"],
  "placebo":     ["sugar pill", "effect", "trial"],
  "peer review": ["scientists check", "journal", "validation"],
  "quasar":      ["bright galaxy core", "distant", "black hole"],
  "pulsar":      ["rotating star", "radio waves", "neutron star"],
  "nebula":      ["gas cloud", "star nursery", "cosmic"],
  "supernova":   ["star explosion", "bright", "remnant"],
  "singularity": ["black hole center", "infinite density", "point"],
  "isotope":     ["same element", "different mass", "atoms"],
  "radioactive": ["decay", "radiation", "unstable"],
  "half-life":   ["decay rate", "radioactive", "time"],
  "fission":     ["split atom", "nuclear", "energy"],
  "fusion":      ["combine atoms", "star power", "hydrogen"],
  "antibody":    ["immune", "protein", "pathogen fighter"],
  "antigen":     ["triggers immune", "foreign", "protein"],
  "pathogen":    ["disease-causing", "bacteria virus", "infection"],
  "mutation":    ["DNA change", "evolution", "gene"],
  "chromosome":  ["DNA strand", "23 pairs", "nucleus"],
  "tectonic":    ["plates", "earthquake", "continental drift"],
  "seismic":     ["earthquake waves", "vibration", "Richter"],
  "magnetic field":["poles", "compass", "Earth"],
  "ionosphere":  ["upper atmosphere", "radio waves", "charged"],
  "troposphere": ["lowest atmosphere", "weather", "breathing"],
  "entropy":     ["disorder", "energy spread", "thermodynamics"],
  "thermodynamics":["heat energy", "laws", "temperature"],
  "kinetics":    ["reaction speed", "rate", "energy"],
  "equilibrium": ["balance", "equal rates", "stable"],
  "resonance":   ["frequency match", "vibration", "amplify"],
  "quantum":     ["discrete energy", "uncertainty", "Planck"],
  "relativity":  ["Einstein", "spacetime", "E=mc²"],
  "uncertainty": ["Heisenberg", "position speed", "quantum"],
  "superposition":["both states", "quantum", "collapse"],
  "entanglement":["linked particles", "quantum", "Einstein"],

  // ── 🏛️ History ───────────────────────────────────────────────────────────────
  "gladiator":   ["arena", "Rome", "combat"],
  "pharaoh":     ["Egypt", "pyramid", "ruler"],
  "crusade":     ["holy war", "Jerusalem", "medieval"],
  "colony":      ["settlement", "overseas", "empire"],
  "revolution":  ["uprising", "overthrow", "change"],
  "siege":       ["surround", "castle", "cut off"],
  "treaty":      ["peace agreement", "signed", "nations"],
  "dynasty":     ["ruling family", "succession", "empire"],
  "plague":      ["Black Death", "epidemic", "medieval"],
  "conquest":    ["military takeover", "territory", "victorious"],
  "renaissance": ["rebirth", "art", "Florence"],
  "reformation": ["Luther", "Protestant", "church split"],
  "inquisition": ["heresy trials", "torture", "church"],
  "schism":      ["split", "church divide", "East West"],
  "heresy":      ["forbidden belief", "church", "punished"],
  "feudalism":   ["lords serfs", "land exchange", "medieval"],
  "serfdom":     ["bound to land", "feudal", "peasant"],
  "guild":       ["craftsmen union", "medieval", "trade"],
  "merchant":    ["trade", "goods", "profit"],
  "armistice":   ["ceasefire", "WWI", "November 11"],
  "blockade":    ["cut off supply", "naval", "siege"],
  "tribunal":    ["court", "judgment", "war crimes"],
  "manifesto":   ["declaration", "political", "published"],
  "propaganda":  ["state message", "persuade", "media"],
  "censorship":  ["suppress", "banned", "information"],
  "exile":       ["banished", "abroad", "Napoleon"],
  "abdication":  ["resign throne", "monarch", "surrender"],
  "succession":  ["inherit throne", "next ruler", "line"],
  "colonialism": ["empire", "subjugate", "resources"],
  "imperialism": ["expand empire", "dominate", "territory"],
  "annexation":  ["absorb territory", "takeover", "forced"],
  "partition":   ["divide territory", "borders", "split"],
  "sovereignty": ["self-rule", "independence", "state"],
  "abolition":   ["end slavery", "movement", "Lincoln"],
  "suffrage":    ["right to vote", "women", "movement"],
  "rebellion":   ["revolt", "uprising", "against authority"],
  "mutiny":      ["crew revolt", "military", "ship"],
  "insurrection":["armed revolt", "citizens", "government"],
  "excavation":  ["dig", "archaeology", "uncover"],
  "artifact":    ["ancient object", "museum", "discovered"],
  "relic":       ["sacred object", "ancient", "preserved"],
  "inscription": ["carved text", "stone", "ancient"],
  "hieroglyphic":["Egypt", "picture writing", "ancient"],
  "papyrus":     ["Egypt", "ancient paper", "reed"],
  "codex":       ["early book", "manuscript", "pages"],
  "scroll":      ["rolled parchment", "ancient", "text"],
  "mosaic":      ["tile art", "ancient", "Byzantine"],
  "fresco":      ["wall painting", "plaster", "Sistine"],

  // ── 🧁 Desserts ──────────────────────────────────────────────────────────────
  "churro":      ["fried dough", "cinnamon sugar", "Spain"],
  "macaron":     ["almond", "French", "colorful"],
  "truffle":     ["chocolate ganache", "rolled", "rich"],
  "sorbet":      ["fruit", "no dairy", "frozen"],
  "custard":     ["egg yolk", "creamy", "baked"],
  "praline":     ["caramelized nuts", "France", "sweet"],
  "mochi":       ["rice cake", "Japan", "chewy"],
  "cannoli":     ["fried shell", "ricotta", "Sicily"],
  "brownie":     ["chocolate", "fudgy", "square"],
  "parfait":     ["layered", "glass", "yogurt fruit"],
  "pavlova":     ["meringue", "cream", "fruit"],
  "profiterole": ["choux pastry", "cream filled", "chocolate"],
  "eclair":      ["choux pastry", "oblong", "chocolate glaze"],
  "tarte tatin": ["upside-down apple", "caramel", "France"],
  "clafoutis":   ["baked", "cherries", "custard batter"],
  "creme brulee":["caramelized top", "custard", "torch"],
  "panna cotta": ["cooked cream", "gelatin", "Italy"],
  "zabaglione":  ["egg yolk", "Marsala", "Italy"],
  "semifreddo":  ["half frozen", "Italian", "creamy"],
  "granita":     ["crushed ice", "Sicily", "flavored"],
  "halva":       ["sesame", "Middle East", "dense"],
  "loukoumades": ["Greek donuts", "honey", "fried"],
  "knafeh":      ["cheese pastry", "syrup", "Palestine"],
  "basbousa":    ["semolina", "syrup", "Middle East"],
  "umm ali":     ["Egyptian bread pudding", "cream", "nuts"],
  "gulab jamun": ["milk solid", "syrup", "India"],
  "jalebi":      ["fried spiral", "syrup", "India"],
  "kulfi":       ["dense ice cream", "India", "mango"],
  "rasgulla":    ["cheese ball", "syrup", "Bengal"],
  "burfi":       ["fudge", "milk solid", "India"],
  "mango sticky rice":["Thailand", "coconut milk", "sweet"],
  "tong sui":    ["sweet soup", "Cantonese", "dessert"],
  "tang yuan":   ["glutinous rice balls", "sesame", "China"],
  "nian gao":    ["sticky cake", "Chinese New Year", "rice"],
  "wife cake":   ["flaky pastry", "melon paste", "Hong Kong"],
  "brigadeiro":  ["chocolate", "Brazil", "condensed milk"],
  "alfajor":     ["sandwich cookie", "dulce de leche", "Argentina"],
  "dulce de leche":["caramel", "Argentina", "milk"],
  "tres leches": ["three milks", "Mexico", "soaked cake"],
  "churros":     ["fried dough", "cinnamon", "Spain"],
  "rugelach":    ["rolled pastry", "Jewish", "cream cheese"],
  "babka":       ["braided bread", "Jewish", "chocolate"],
  "sufganiyah":  ["Hanukkah donut", "jelly filled", "Israel"],
  "hamantaschen":["triangular cookie", "Purim", "filled"],
  "mandelbrot":  ["twice-baked", "Jewish", "almonds"],
  "lamington":   ["sponge cake", "chocolate coconut", "Australia"],
  "sticky date": ["pudding", "Australia", "toffee sauce"],
  "anzac biscuit":["oat", "Australia", "golden syrup"],
  "hedgehog slice":["no-bake", "chocolate", "Australia"],

  // ── 🌃 Cities ────────────────────────────────────────────────────────────────
  "Tokyo":       ["Shibuya", "sushi", "Japan"],
  "Cairo":       ["pyramids", "Nile", "Egypt"],
  "Venice":      ["canals", "gondola", "Italy"],
  "Nairobi":     ["safari", "Kenya", "savanna"],
  "Reykjavik":   ["aurora", "Iceland", "geothermal"],
  "Montreal":    ["French", "Canada", "poutine"],
  "Havana":      ["Cuba", "cigars", "vintage cars"],
  "Istanbul":    ["Bosphorus", "Turkey", "mosques"],
  "Seoul":       ["K-pop", "Korea", "Han River"],
  "Lisbon":      ["trams", "Portugal", "fado"],
  "Lagos":       ["Nigeria", "Africa", "megacity"],
  "Kinshasa":    ["Congo River", "DRC", "Africa"],
  "Casablanca":  ["Morocco", "port", "Atlantic"],
  "Algiers":     ["Algeria", "Mediterranean", "whitewashed"],
  "Addis Ababa": ["Ethiopia", "altitude", "African Union"],
  "Karachi":     ["Pakistan", "port", "largest city"],
  "Dhaka":       ["Bangladesh", "density", "textile"],
  "Mumbai":      ["Bollywood", "India", "gateway"],
  "Chennai":     ["South India", "Tamil", "Marina Beach"],
  "Kolkata":     ["Bengal", "India", "colonial"],
  "Jakarta":     ["Indonesia", "sinking", "traffic"],
  "Manila":      ["Philippines", "archipelago", "traffic"],
  "Kuala Lumpur":["Petronas towers", "Malaysia", "multicultural"],
  "Bangkok":     ["Thailand", "temples", "street food"],
  "Ho Chi Minh": ["Vietnam", "Saigon", "motorbikes"],
  "Bogota":      ["Colombia", "Andes", "altitude"],
  "Lima":        ["Peru", "Pacific", "ceviche"],
  "Santiago":    ["Chile", "Andes", "copper"],
  "Quito":       ["Ecuador", "equator", "altitude"],
  "Caracas":     ["Venezuela", "mountains", "capital"],
  "Warsaw":      ["Poland", "WWII", "rebuilt"],
  "Prague":      ["Czechia", "castle", "medieval"],
  "Budapest":    ["Hungary", "baths", "Danube"],
  "Bucharest":   ["Romania", "Communist era", "Balkans"],
  "Sofia":       ["Bulgaria", "Balkans", "ancient"],
  "Oslo":        ["Norway", "fjords", "Nobel Prize"],
  "Stockholm":   ["Sweden", "ABBA", "archipelago"],
  "Helsinki":    ["Finland", "design", "Baltic"],
  "Copenhagen":  ["Denmark", "Nyhavn", "hygge"],
  "Amsterdam":   ["canals", "Netherlands", "bicycles"],
  "Brussels":    ["Belgium", "EU headquarters", "waffles"],
  "Zurich":      ["Switzerland", "banking", "Alps"],
  "Vienna":      ["Austria", "Mozart", "coffee houses"],
  "Athens":      ["Greece", "Parthenon", "ancient"],
  "Dubrovnik":   ["Croatia", "Game of Thrones", "walled city"],
  "Marrakech":   ["Morocco", "souk", "medina"],
  "Tunis":       ["Tunisia", "Mediterranean", "Carthage"],
  "Accra":       ["Ghana", "West Africa", "coastal"],
  "Dakar":       ["Senegal", "westernmost Africa", "peninsula"],
  "Dar es Salaam":["Tanzania", "Indian Ocean", "port"],

  // ── 🧠 Emotions ──────────────────────────────────────────────────────────────
  "nostalgia":   ["past memories", "longing", "childhood"],
  "euphoria":    ["intense joy", "peak feeling", "elation"],
  "envy":        ["wanting what others have", "jealousy", "resentment"],
  "dread":       ["impending fear", "heavy", "foreboding"],
  "longing":     ["deep desire", "distance", "yearning"],
  "awe":         ["overwhelm", "vastness", "wonder"],
  "guilt":       ["wrongdoing", "regret", "moral"],
  "pride":       ["accomplishment", "self-worth", "satisfaction"],
  "spite":       ["revenge", "petty", "contrary"],
  "apathy":      ["indifference", "no feeling", "detached"],
  "melancholy":  ["gentle sadness", "reflective", "pensive"],
  "elation":     ["great joy", "high spirits", "uplifted"],
  "remorse":     ["deep regret", "sorry", "guilt"],
  "yearning":    ["deep longing", "unattainable", "desire"],
  "contempt":    ["disdain", "superiority", "looking down"],
  "serenity":    ["calm", "peace", "stillness"],
  "anxiety":     ["worry", "tension", "uncertain"],
  "frustration": ["blocked goals", "irritation", "stuck"],
  "resentment":  ["held grudge", "bitter", "unfairness"],
  "gratitude":   ["thankful", "appreciation", "blessing"],
  "schadenfreude":["joy at others' misfortune", "German", "smug"],
  "saudade":     ["Portuguese longing", "bittersweet", "absent"],
  "hiraeth":     ["Welsh homesickness", "longing", "unreachable"],
  "mono no aware":["Japanese impermanence", "bittersweet", "fleeting"],
  "wabi-sabi":   ["Japanese beauty", "imperfection", "transience"],
  "fernweh":     ["wanderlust", "German", "far away"],
  "wanderlust":  ["travel desire", "explore", "restless"],
  "sehnsucht":   ["deep longing", "German", "life unlived"],
  "torschlusspanik":["door closing panic", "German", "time running out"],
  "weltschmerz": ["world pain", "German", "sadness"],
  "vulnerability":["exposed", "open", "defenseless"],
  "embarrassment":["social mistake", "flush", "awkward"],
  "shame":       ["deep wrong", "hide", "self-judgment"],
  "humiliation": ["public shame", "dignity lost", "degraded"],
  "mortification":["extreme embarrassment", "humbled", "crushed"],
  "anticipation":["looking forward", "excitement", "waiting"],
  "suspense":    ["uncertain outcome", "tension", "waiting"],
  "curiosity":   ["wanting to know", "explore", "questions"],
  "wonder":      ["amazement", "childlike", "awe"],
  "fascination": ["captivated", "drawn in", "absorbed"],
  "boredom":     ["nothing interesting", "monotony", "restless"],
  "restlessness":["can't settle", "agitated", "movement"],
  "dissatisfaction":["not enough", "wanting more", "unfulfilled"],
  "disillusionment":["lost faith", "reality check", "bitter"],
  "resignation": ["acceptance", "giving up", "surrender"],
  "tenderness":  ["gentle care", "soft", "affectionate"],
  "compassion":  ["empathy for suffering", "kindness", "others"],
  "adoration":   ["deep love", "worship", "devotion"],
  "devotion":    ["loyalty", "dedication", "faithfulness"],
  "reverence":   ["deep respect", "awe", "sacred"],
};
